"""empty message

Revision ID: 751f83a991e6
Revises: 
Create Date: 2017-01-31 01:11:39.503707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751f83a991e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crontab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.String(length=50), nullable=True),
    sa.Column('hour', sa.String(length=50), nullable=True),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('day_of_month', sa.String(length=50), nullable=True),
    sa.Column('month_of_year', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('every', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('task', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('worker', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('task', sa.String(length=100), nullable=True),
    sa.Column('task_args', sa.Text(), nullable=True),
    sa.Column('task_kwargs', sa.Text(), nullable=True),
    sa.Column('crontab_id', sa.Integer(), nullable=True),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('queue', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=200), nullable=True),
    sa.Column('routing_key', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crontab_id'], ['crontab.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['interval.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_task')
    op.drop_table('task_result')
    op.drop_table('interval')
    op.drop_table('crontab')
    # ### end Alembic commands ###
